import React, { useState, useEffect } from 'react';
import { useDisabilityContext, DeniedCondition } from '../contexts/DisabilityContext';

interface QuestionnaireData {
  diagnosedDuringService: boolean;
  ongoingSymptoms: boolean;
  mentionedInVAExams: boolean;
  believedSecondary: boolean;
  relatedCondition: string;
  symptomsDescription: string;
  treatmentHistory: string;
  additionalNotes: string;
}

interface AITheoryResponse {
  theory: string;
  nexusLogic: string;
  cfrReferences: string[];
  medicalRationale: string;
  suggestedEvidence: string[];
}

export const EnhancedEntitlementHelper: React.FC = () => {
  const { serviceConnectedConditions, deniedConditions, addDeniedCondition, updateDeniedCondition, removeDeniedCondition } = useDisabilityContext();

  const [expandedConditionId, setExpandedConditionId] = useState<string | null>(null);
  const [loadingTheory, setLoadingTheory] = useState<{ [key: string]: boolean }>({});
  const [showQuestionnaire, setShowQuestionnaire] = useState<{ [key: string]: boolean }>({});

  const connectionTypes = [
    { value: 'direct', label: 'Direct Service Connection', icon: '⚡' },
    { value: 'secondary', label: 'Secondary Service Connection', icon: '🔗' },
    { value: 'aggravation', label: 'Aggravation of Pre-Existing', icon: '📈' },
    { value: 'presumptive', label: 'Presumptive Service Connection', icon: '📋' },
    { value: 'concurrent', label: 'Concurrent Service', icon: '⚖️' }
  ];

  const createNewDeniedCondition = () => {
    const newCondition: DeniedCondition = {
      id: Date.now().toString(),
      name: '',
      connectionType: 'direct',
      description: '',
      serviceHistory: '',
      diagnosedDuringService: false,
      ongoingSymptoms: false,
      mentionedInVAExams: false,
      believedSecondary: false,
      symptoms: [],
      treatment: [],
      nexusEvidence: [],
      questionnaire: {
        diagnosedDuringService: false,
        ongoingSymptoms: false,
        mentionedInVAExams: false,
        believedSecondary: false,
        relatedCondition: '',
        symptomsDescription: '',
        treatmentHistory: '',
        additionalNotes: ''
      }
    };
    addDeniedCondition(newCondition);
    setExpandedConditionId(newCondition.id);
  };

  const generateAITheory = async (conditionId: string) => {
    const condition = deniedConditions.find(c => c.id === conditionId);
    if (!condition) return;

    setLoadingTheory({ ...loadingTheory, [conditionId]: true });

    try {
      const response = await fetch('/api/entitlement/generate-theory', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          deniedCondition: condition,
          serviceConnectedConditions: serviceConnectedConditions,
          questionnaire: condition.questionnaire
        })
      });

      const data: AITheoryResponse = await response.json();

      updateDeniedCondition(conditionId, {
        aiTheory: data.theory,
        aiReferences: data.cfrReferences,
        aiMedicalRationale: data.medicalRationale
      });
    } catch (error) {
      console.error('Error generating theory:', error);
      updateDeniedCondition(conditionId, {
        aiTheory: 'Error generating theory. Please try again or contact support.'
      });
    } finally {
      setLoadingTheory({ ...loadingTheory, [conditionId]: false });
    }
  };

  const updateQuestionnaireField = (conditionId: string, field: keyof QuestionnaireData, value: any) => {
    const condition = deniedConditions.find(c => c.id === conditionId);
    if (!condition || !condition.questionnaire) return;

    const updatedQuestionnaire = {
      ...condition.questionnaire,
      [field]: value
    };

    updateDeniedCondition(conditionId, { questionnaire: updatedQuestionnaire });
  };

  const copyTheoryToClipboard = (conditionId: string) => {
    const condition = deniedConditions.find(c => c.id === conditionId);
    if (!condition || !condition.aiTheory) return;

    const text = `
THEORY OF ENTITLEMENT - ${condition.name.toUpperCase()}
Connection Type: ${condition.connectionType}

${condition.aiTheory}

MEDICAL RATIONALE:
${condition.aiMedicalRationale || 'N/A'}

CFR REFERENCES:
${condition.aiReferences?.join('\n') || 'N/A'}

---
This is educational information only and does not constitute legal advice.
Generated by Vets Ready Entitlement Helper
    `.trim();

    navigator.clipboard.writeText(text);
    alert('Theory copied to clipboard!');
  };

  const exportToPDF = async () => {
    // This will be implemented in the PDF export utility
    const response = await fetch('/api/entitlement/export-pdf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        deniedConditions,
        serviceConnectedConditions
      })
    });

    const blob = await response.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `entitlement-theories-${new Date().toISOString().split('T')[0]}.pdf`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-6 rounded-lg shadow-lg">
        <h2 className="text-2xl font-bold mb-2">🎯 Enhanced Entitlement Helper</h2>
        <p className="text-blue-100">
          Build strong theories of entitlement for denied conditions using AI-powered analysis and your existing service-connected disabilities.
        </p>
      </div>

      {/* Service-Connected Conditions Display */}
      {serviceConnectedConditions.length > 0 && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="text-lg font-semibold text-green-800 mb-3">
            ✅ Your Service-Connected Conditions ({serviceConnectedConditions.length})
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
            {serviceConnectedConditions.map(condition => (
              <div key={condition.id} className="bg-white rounded px-3 py-2 border border-green-300">
                <div className="font-medium text-gray-800">{condition.name || 'Unnamed'}</div>
                <div className="text-sm text-gray-600">Rating: {condition.rating}%</div>
              </div>
            ))}
          </div>
          <p className="text-sm text-green-700 mt-3">
            💡 These conditions will be used to identify potential secondary connections for your denied claims.
          </p>
        </div>
      )}

      {serviceConnectedConditions.length === 0 && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <h3 className="text-lg font-semibold text-yellow-800 mb-2">
            ⚠️ No Service-Connected Conditions Found
          </h3>
          <p className="text-yellow-700">
            Add your service-connected disabilities in the <strong>Calculator</strong> tab first. This will help the AI identify potential secondary connections.
          </p>
        </div>
      )}

      {/* Add New Denied Condition Button */}
      <div className="flex justify-between items-center">
        <h3 className="text-xl font-bold text-gray-800">Denied Conditions</h3>
        <button
          onClick={createNewDeniedCondition}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
        >
          + Add Denied Condition
        </button>
      </div>

      {/* Denied Conditions List */}
      {deniedConditions.length === 0 && (
        <div className="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
          <p className="text-gray-600 text-lg mb-2">No denied conditions added yet</p>
          <p className="text-gray-500 text-sm">Click "Add Denied Condition" to get started</p>
        </div>
      )}

      {deniedConditions.map(condition => (
        <div key={condition.id} className="bg-white border border-gray-300 rounded-lg shadow-md overflow-hidden">
          {/* Condition Header */}
          <div className="bg-gray-100 p-4 flex justify-between items-center">
            <div className="flex-1">
              <input
                type="text"
                value={condition.name}
                onChange={(e) => updateDeniedCondition(condition.id, { name: e.target.value })}
                placeholder="Condition Name (e.g., Sleep Apnea)"
                className="w-full text-lg font-semibold bg-transparent border-none focus:outline-none focus:ring-2 focus:ring-blue-500 rounded px-2 py-1"
              />
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => setExpandedConditionId(expandedConditionId === condition.id ? null : condition.id)}
                className="text-blue-600 hover:text-blue-800 px-3 py-1 rounded"
              >
                {expandedConditionId === condition.id ? '▲ Collapse' : '▼ Expand'}
              </button>
              <button
                onClick={() => removeDeniedCondition(condition.id)}
                className="text-red-600 hover:text-red-800 px-3 py-1 rounded"
              >
                🗑️ Delete
              </button>
            </div>
          </div>

          {/* Expanded Content */}
          {expandedConditionId === condition.id && (
            <div className="p-6 space-y-6">
              {/* Connection Type */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Connection Type
                </label>
                <select
                  value={condition.connectionType}
                  onChange={(e) => updateDeniedCondition(condition.id, { connectionType: e.target.value as any })}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                >
                  {connectionTypes.map(type => (
                    <option key={type.value} value={type.value}>
                      {type.icon} {type.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Condition Description
                </label>
                <textarea
                  value={condition.description}
                  onChange={(e) => updateDeniedCondition(condition.id, { description: e.target.value })}
                  placeholder="Describe the condition, symptoms, and how it affects you..."
                  rows={3}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                />
              </div>

              {/* Service History */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Service History / Timeline
                </label>
                <textarea
                  value={condition.serviceHistory}
                  onChange={(e) => updateDeniedCondition(condition.id, { serviceHistory: e.target.value })}
                  placeholder="When did symptoms start? What happened during service? When was it first diagnosed?"
                  rows={3}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                />
              </div>

              {/* Questionnaire Toggle */}
              <div>
                <button
                  onClick={() => setShowQuestionnaire({ ...showQuestionnaire, [condition.id]: !showQuestionnaire[condition.id] })}
                  className="text-blue-600 hover:text-blue-800 font-medium flex items-center gap-2"
                >
                  {showQuestionnaire[condition.id] ? '▼' : '▶'}
                  {showQuestionnaire[condition.id] ? 'Hide' : 'Show'} Guided Questionnaire (Recommended)
                </button>
              </div>

              {/* Questionnaire */}
              {showQuestionnaire[condition.id] && condition.questionnaire && (
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 space-y-4">
                  <h4 className="font-semibold text-blue-900">Guided Questionnaire</h4>

                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={condition.questionnaire.diagnosedDuringService}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'diagnosedDuringService', e.target.checked)}
                      className="w-5 h-5"
                    />
                    <label className="text-gray-800">Was this condition diagnosed during service?</label>
                  </div>

                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={condition.questionnaire.ongoingSymptoms}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'ongoingSymptoms', e.target.checked)}
                      className="w-5 h-5"
                    />
                    <label className="text-gray-800">Do you have ongoing symptoms?</label>
                  </div>

                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={condition.questionnaire.mentionedInVAExams}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'mentionedInVAExams', e.target.checked)}
                      className="w-5 h-5"
                    />
                    <label className="text-gray-800">Is it mentioned in any prior VA exams?</label>
                  </div>

                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={condition.questionnaire.believedSecondary}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'believedSecondary', e.target.checked)}
                      className="w-5 h-5"
                    />
                    <label className="text-gray-800">Do you believe it's secondary to another condition?</label>
                  </div>

                  {condition.questionnaire.believedSecondary && (
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Which service-connected condition is it related to?
                      </label>
                      <select
                        value={condition.questionnaire.relatedCondition}
                        onChange={(e) => updateQuestionnaireField(condition.id, 'relatedCondition', e.target.value)}
                        className="w-full border border-gray-300 rounded-lg px-4 py-2"
                      >
                        <option value="">Select a condition...</option>
                        {serviceConnectedConditions.map(sc => (
                          <option key={sc.id} value={sc.name}>
                            {sc.name} ({sc.rating}%)
                          </option>
                        ))}
                      </select>
                    </div>
                  )}

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Describe your symptoms in detail
                    </label>
                    <textarea
                      value={condition.questionnaire.symptomsDescription}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'symptomsDescription', e.target.value)}
                      placeholder="Frequency, severity, triggers, impact on daily life..."
                      rows={3}
                      className="w-full border border-gray-300 rounded-lg px-4 py-2"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Treatment history
                    </label>
                    <textarea
                      value={condition.questionnaire.treatmentHistory}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'treatmentHistory', e.target.value)}
                      placeholder="Medications, therapies, procedures, dates..."
                      rows={3}
                      className="w-full border border-gray-300 rounded-lg px-4 py-2"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Additional notes
                    </label>
                    <textarea
                      value={condition.questionnaire.additionalNotes}
                      onChange={(e) => updateQuestionnaireField(condition.id, 'additionalNotes', e.target.value)}
                      placeholder="Any other relevant information..."
                      rows={2}
                      className="w-full border border-gray-300 rounded-lg px-4 py-2"
                    />
                  </div>
                </div>
              )}

              {/* Generate Theory Button */}
              <div className="flex gap-3">
                <button
                  onClick={() => generateAITheory(condition.id)}
                  disabled={loadingTheory[condition.id] || !condition.name || !condition.description}
                  className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 disabled:from-gray-400 disabled:to-gray-400 text-white px-6 py-3 rounded-lg font-medium transition-colors"
                >
                  {loadingTheory[condition.id] ? (
                    <span className="flex items-center justify-center gap-2">
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      Generating Theory...
                    </span>
                  ) : (
                    '🤖 Generate AI Theory of Entitlement'
                  )}
                </button>
              </div>

              {/* AI Theory Output */}
              {condition.aiTheory && (
                <div className="bg-gradient-to-br from-purple-50 to-blue-50 border-2 border-purple-300 rounded-lg p-6 space-y-4">
                  <div className="flex justify-between items-start">
                    <h4 className="text-lg font-bold text-purple-900">📜 AI-Generated Theory of Entitlement</h4>
                    <button
                      onClick={() => copyTheoryToClipboard(condition.id)}
                      className="bg-white hover:bg-gray-100 text-purple-700 px-3 py-1 rounded border border-purple-300 text-sm"
                    >
                      📋 Copy
                    </button>
                  </div>

                  <div className="prose max-w-none">
                    <div className="whitespace-pre-wrap text-gray-800 leading-relaxed">
                      {condition.aiTheory}
                    </div>
                  </div>

                  {condition.aiMedicalRationale && (
                    <div className="bg-white rounded-lg p-4 border border-purple-200">
                      <h5 className="font-semibold text-purple-900 mb-2">🏥 Medical Rationale</h5>
                      <p className="text-gray-700 whitespace-pre-wrap">{condition.aiMedicalRationale}</p>
                    </div>
                  )}

                  {condition.aiReferences && condition.aiReferences.length > 0 && (
                    <div className="bg-white rounded-lg p-4 border border-purple-200">
                      <h5 className="font-semibold text-purple-900 mb-2">📚 CFR References</h5>
                      <ul className="list-disc list-inside space-y-1">
                        {condition.aiReferences.map((ref, idx) => (
                          <li key={idx} className="text-gray-700">{ref}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div className="bg-yellow-50 border border-yellow-300 rounded p-3 text-sm text-yellow-800">
                    ⚠️ <strong>Educational Only:</strong> This theory is AI-generated for educational purposes and does not constitute legal advice.
                    Consult with a VSO or VA-accredited attorney for your specific case.
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      ))}

      {/* Export All Button */}
      {deniedConditions.length > 0 && (
        <div className="flex justify-center">
          <button
            onClick={exportToPDF}
            className="bg-green-600 hover:bg-green-700 text-white px-8 py-3 rounded-lg font-medium flex items-center gap-2"
          >
            📄 Export All Theories to PDF
          </button>
        </div>
      )}

      {/* Instructions */}
      <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
        <h3 className="text-lg font-bold text-gray-800 mb-3">📖 How to Use This Tool</h3>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li>First, add your service-connected conditions in the <strong>Calculator</strong> tab</li>
          <li>Click "Add Denied Condition" to create a new entry for each denied claim</li>
          <li>Fill in the condition details: name, connection type, description, and service history</li>
          <li>Optionally complete the guided questionnaire for more accurate AI analysis</li>
          <li>Click "Generate AI Theory of Entitlement" to get an educational theory</li>
          <li>Review the AI-generated theory, medical rationale, and CFR references</li>
          <li>Copy individual theories or export all to PDF for claim strategy planning</li>
          <li>Use these theories to discuss your claim with a VSO or attorney</li>
        </ol>
      </div>
    </div>
  );
};
