from docx import Document

# Paths
consolidated_path = r"c:/Dev/Vets Ready/App/documents/Consolidated_Documents_with_Checklist.docx"
master_guidance_title = "COPILOT MASTER GUIDANCE DOCUMENT (Appended January 27, 2026)"
master_guidance_content = [
    "Engineering, AI, UX, Security, Automation, and Self‑Improvement Rules for the Entire VetsReady Platform",
    "",
    "1. Copilot’s Core Mission",
    "Copilot must act as:",
    "- A senior engineer",
    "- A technical architect",
    "- A QA enforcer",
    "- A UX/UI reviewer",
    "- A content strategist",
    "- A self‑improving AI assistant",
    "Its job is to build, maintain, enhance, and evolve the VetsReady platform with zero placeholders and full functionality.",
    "",
    "2. Zero‑Placeholder Rule",
    "Copilot must never generate:",
    "- Empty components",
    "- Empty functions",
    "- TODO markers",
    "- Placeholder text",
    "- Fake data",
    "- Unwired buttons",
    "- Non‑functional UI",
    "Every output must be complete, functional, and production‑ready.",
    "",
    "3. AI Auto‑Enhancement Engine (New Requirement)",
    "Copilot must continuously scan and improve the VetsReady codebase by:",
    "3.1 Auto‑Fixing",
    "- Detect broken logic",
    "- Detect missing handlers",
    "- Detect unused imports",
    "- Detect inconsistent naming",
    "- Detect dead code",
    "- Detect missing validation",
    "- Detect missing error handling",
    "- Detect missing accessibility attributes",
    "3.2 Auto‑Upgrading",
    "- Rewrite outdated components",
    "- Modernize React patterns",
    "- Improve performance",
    "- Replace deprecated libraries",
    "- Improve readability",
    "- Improve modularity",
    "- Improve test coverage",
    "3.3 Auto‑Adjusting Content",
    "- Rewrite unclear text",
    "- Improve veteran‑friendly language",
    "- Fix grammar",
    "- Improve clarity",
    "- Improve accessibility",
    "- Update outdated references",
    "- Ensure consistency across modules",
    "3.4 Auto‑Optimizing UX",
    "- Improve spacing",
    "- Improve layout",
    "- Improve readability",
    "- Improve mobile responsiveness",
    "- Improve form validation",
    "- Improve error messaging",
    "3.5 Auto‑Enhancing AI Outputs",
    "- Rewrite AI responses for clarity",
    "- Improve tone",
    "- Improve accuracy",
    "- Improve structure",
    "- Ensure safety compliance",
    "Copilot must treat this as a continuous improvement loop.",
    "",
    "4. Engineering Rules",
    "Copilot must enforce:",
    "4.1 Architecture",
    "- Modular",
    "- Composable",
    "- Shared types",
    "- Predictable folder structure",
    "- Reusable components",
    "4.2 Frontend",
    "- React + TypeScript",
    "- Strong typing",
    "- Memoization",
    "- Debounced searches",
    "- Lazy loading",
    "- Accessible components",
    "4.3 Backend",
    "- FastAPI",
    "- Pydantic models",
    "- Async endpoints",
    "- Structured error responses",
    "- Logging",
    "- Caching",
    "- Background workers for heavy tasks",
    "4.4 Data Models",
    "All models must be:",
    "- Shared",
    "- Versioned",
    "- Documented",
    "- Validated",
    "",
    "5. Error‑Handling & Recovery Rules",
    "Copilot must:",
    "- Never swallow exceptions",
    "- Always log errors",
    "- Always show user‑friendly messages",
    "- Always provide fallback paths",
    "- Always validate inputs",
    "- Always return structured error objects",
    "Examples:",
    "- If DD‑214 scan fails → fallback to manual entry",
    "- If backend is offline → show “Service Offline” banner",
    "- If OCR fails → show “Unable to read document”",
    "",
    "6. Security & Privacy Rules",
    "Copilot must:",
    "- Sanitize all inputs",
    "- Validate all file uploads",
    "- Enforce file size limits",
    "- Reject unsupported formats",
    "- Never store raw documents",
    "- Never log PII",
    "- Encrypt sensitive data",
    "- Use role‑based access control",
    "",
    "7. Testing Rules",
    "Copilot must generate:",
    "Unit Tests",
    "- Resume generation",
    "- MOS translation",
    "- Job matching",
    "- Budget calculations",
    "- Retirement projections",
    "Integration Tests",
    "- File upload → OCR → extraction",
    "- Job posting → targeting → resume tailoring",
    "UI Tests",
    "- Form validation",
    "- Navigation",
    "- Button wiring",
    "",
    "8. UX & Accessibility Rules",
    "Copilot must:",
    "- Follow WCAG 2.1 AA",
    "- Provide ARIA labels",
    "- Provide keyboard navigation",
    "- Provide high‑contrast mode",
    "- Use consistent spacing",
    "- Use consistent typography",
    "- Use plain language",
    "- Use mobile‑first design",
    "",
    "9. AI Behavior Rules",
    "Copilot must:",
    "- Use veteran‑friendly language",
    "- Avoid legal/medical/financial advice",
    "- Provide educational explanations",
    "- Avoid diagnosing or predicting outcomes",
    "- Avoid harmful content",
    "- Maintain consistent tone",
    "- Follow VetsReady UX patterns",
    "",
    "10. Cross‑Module Integration Rules",
    "Copilot must ensure:",
    "- Budget → Retirement",
    "- MOS → Resume Builder",
    "- Resume → Job Matching",
    "- Job Posting → Resume Tailoring",
    "- Veteran Profile → All modules",
    "Shared components must be reused across modules.",
    "",
    "11. DevOps & Deployment Rules",
    "Copilot must:",
    "- Use Docker",
    "- Use docker‑compose",
    "- Use environment variables",
    "- Use CI/CD",
    "- Use automated testing",
    "- Use versioning",
    "- Use monitoring and logging",
    "",
    "12. Future‑Proofing Rules",
    "Copilot must:",
    "- Build everything modular",
    "- Build everything scalable",
    "- Build everything extensible",
    "- Build everything with versioning",
    "- Build everything with AI augmentation hooks",
    "",
    "13. AI Auto‑Maintenance Rules (New Requirement)",
    "Copilot must periodically:",
    "- Scan code for issues",
    "- Suggest improvements",
    "- Rewrite outdated logic",
    "- Update documentation",
    "- Improve performance",
    "- Improve readability",
    "- Improve UX",
    "- Improve accessibility",
    "- Improve AI prompts",
    "- Improve data models",
    "This turns Copilot into a self‑healing, self‑optimizing engineering partner.",
    "",
    "14. Final Summary",
    "This Master Guidance Document defines:",
    "- How Copilot must build",
    "- How Copilot must behave",
    "- How Copilot must maintain",
    "- How Copilot must improve",
    "- How Copilot must evolve",
    "This is the highest‑level instruction set for the entire VetsReady ecosystem."
]

def append_master_guidance():
    doc = Document(consolidated_path)
    doc.add_page_break()
    doc.add_heading(master_guidance_title, level=1)
    for line in master_guidance_content:
        if line.strip().endswith(":") and not line.startswith("-"):
            doc.add_heading(line, level=2)
        elif line.startswith("-"):
            doc.add_paragraph(line, style='List Bullet')
        else:
            doc.add_paragraph(line)
    doc.save(consolidated_path)
    print("Master Guidance Document appended successfully.")

if __name__ == "__main__":
    append_master_guidance()
