"""
Pydantic schemas for AI-related requests and responses.

These schemas define the structure of data for AI-powered features including
theory generation, secondary condition suggestions, and AI chat.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class PolicyReference(BaseModel):
    """Legal/policy reference (CFR, M21-1, case law)"""
    source: str = Field(..., description="Source citation (e.g., '38 CFR § 3.303')")
    citation: str = Field(..., description="Title or description of the reference")
    relevance: str = Field(..., description="Why this reference applies to the condition")


class EvidenceRecommendation(BaseModel):
    """Recommended evidence for supporting a claim"""
    type: Literal['medical', 'service-records', 'lay-statement', 'nexus-opinion'] = Field(
        ..., description="Type of evidence"
    )
    description: str = Field(..., description="What evidence to obtain")
    priority: Literal['critical', 'important', 'helpful'] = Field(
        ..., description="Importance of this evidence"
    )
    where_to_obtain: Optional[str] = Field(
        None, alias="whereToObtain", description="Guidance on where to get this evidence"
    )

    class Config:
        populate_by_name = True


class AiEntitlementTheory(BaseModel):
    """AI-generated theory of entitlement for a condition"""
    primary_theory: str = Field(
        ..., alias="primaryTheory", description="Main theory of entitlement"
    )
    policy_references: List[PolicyReference] = Field(
        ..., alias="policyReferences", description="CFR and legal references"
    )
    recommended_evidence: List[EvidenceRecommendation] = Field(
        ..., alias="recommendedEvidence", description="Evidence recommendations"
    )
    strength_assessment: Literal['strong', 'moderate', 'weak'] = Field(
        ..., alias="strengthAssessment", description="Strength of the theory"
    )
    challenges: Optional[List[str]] = Field(
        None, description="Potential obstacles or challenges"
    )
    opportunities: Optional[List[str]] = Field(
        None, description="Favorable factors or opportunities"
    )
    nexus_rationale: Optional[str] = Field(
        None, alias="nexusRationale", description="Explanation of medical nexus (for secondary)"
    )

    class Config:
        populate_by_name = True


class DisabilityInput(BaseModel):
    """Input disability for theory generation"""
    id: Optional[str] = None
    name: str
    rating: Optional[int] = None
    service_connection_type: Literal['direct', 'secondary', 'aggravation', 'presumptive'] = Field(
        ..., alias="serviceConnectionType"
    )
    linked_to_ids: Optional[List[str]] = Field(None, alias="linkedToIds")
    diagnosed_in_service: Optional[bool] = Field(None, alias="diagnosedInService")
    current_diagnosis: Optional[bool] = Field(None, alias="currentDiagnosis")
    symptoms_during_service: Optional[bool] = Field(None, alias="symptomsDuringService")

    class Config:
        populate_by_name = True


class TheoryRequest(BaseModel):
    """Request to generate a theory of entitlement"""
    condition: DisabilityInput = Field(..., description="The condition to generate a theory for")
    primary_conditions: Optional[List[DisabilityInput]] = Field(
        None, alias="primaryConditions", description="Service-connected conditions (for secondary)"
    )

    class Config:
        populate_by_name = True


class TheoryResponse(BaseModel):
    """Response containing generated theory"""
    theory: AiEntitlementTheory = Field(..., description="The generated theory")
    disclaimer: str = Field(
        default="This theory was generated by AI and is for educational purposes only. "
        "It is not legal advice. Consult with an accredited VSO or attorney.",
        description="Educational disclaimer"
    )


class AiSuggestion(BaseModel):
    """AI-generated secondary condition suggestion"""
    condition_name: str = Field(..., alias="conditionName", description="Suggested condition name")
    medical_basis: str = Field(
        ..., alias="medicalBasis", description="Medical literature/research basis"
    )
    commonality: Literal['very-common', 'common', 'possible', 'rare'] = Field(
        ..., description="How common this secondary connection is"
    )
    va_approval_pattern: str = Field(
        ..., alias="vaApprovalPattern", description="Historical VA approval patterns"
    )
    confidence: float = Field(..., ge=0.0, le=1.0, description="AI confidence score (0-1)")
    estimated_rating: Optional[str] = Field(
        None, alias="estimatedRating", description="Estimated rating range (e.g., '10-30%')"
    )

    class Config:
        populate_by_name = True


class SecondarySuggestionsRequest(BaseModel):
    """Request to get secondary condition suggestions"""
    primary_condition: DisabilityInput = Field(
        ..., alias="primaryCondition", description="The primary service-connected condition"
    )

    class Config:
        populate_by_name = True


class SecondarySuggestionsResponse(BaseModel):
    """Response containing secondary condition suggestions"""
    suggestions: List[AiSuggestion] = Field(..., description="List of suggested secondary conditions")
    disclaimer: str = Field(
        default="These suggestions are AI-generated based on medical literature and VA patterns. "
        "They are educational only and not medical diagnoses. Consult a healthcare professional.",
        description="Educational disclaimer"
    )


class ChatMessage(BaseModel):
    """Chat message in AI Battle Buddy conversation"""
    role: Literal['user', 'assistant', 'system'] = Field(..., description="Message role")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """Request to AI Battle Buddy chat"""
    messages: List[ChatMessage] = Field(..., description="Conversation history")
    context: Optional[dict] = Field(
        None, description="User's claim context (wizard state, conditions, etc.)"
    )


class ChatResponse(BaseModel):
    """Response from AI Battle Buddy"""
    message: ChatMessage = Field(..., description="Assistant's response message")
    disclaimer: str = Field(
        default="I'm an AI assistant providing educational information only. "
        "I cannot provide legal or medical advice. Consult with qualified professionals.",
        description="Educational disclaimer"
    )


class ClaimStrategyAnalysis(BaseModel):
    """Analysis of overall claim strategy"""
    complexity: Literal['simple', 'medium', 'complex'] = Field(
        ..., description="Complexity level of the claim strategy"
    )
    total_conditions: int = Field(..., alias="totalConditions")
    service_connected_count: int = Field(..., alias="serviceConnectedCount")
    candidate_count: int = Field(..., alias="candidateCount")
    denied_count: int = Field(..., alias="deniedCount")
    recommendations: List[str] = Field(..., description="Strategic recommendations")
    professional_assistance_recommended: bool = Field(
        ..., alias="professionalAssistanceRecommended"
    )

    class Config:
        populate_by_name = True


class ClaimStrategyRequest(BaseModel):
    """Request to analyze claim strategy"""
    service_connected: List[DisabilityInput] = Field(
        ..., alias="serviceConnected", description="Current service-connected disabilities"
    )
    candidates: List[DisabilityInput] = Field(..., description="Planned or current claims")
    denied: List[DisabilityInput] = Field([], description="Previously denied conditions")

    class Config:
        populate_by_name = True


class ClaimStrategyResponse(BaseModel):
    """Response with claim strategy analysis"""
    analysis: ClaimStrategyAnalysis
